apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-http-ingress-external
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "le-prod"
spec:
  ingressClassName: external-nginx
  rules:
    - http:
        paths:
          - path: /api/webhook
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: http
      host: argocd.lab.gravitytech.io
  tls:
    - hosts:
        - argocd.lab.gravitytech.io
      secretName: argocd-ingress-tls-cert
