apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flux-eraser
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: eraser
spec:
  project: default
  source:
    repoURL: https://github.com/brabe/k3s-lab-gitops
    targetRevision: HEAD
    path: apps/eraser

  # Destination cluster and namespace to deploy the application
  destination:
    name: in-cluster
    namespace: flux-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
