apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: arc-system
  namespace: arc-system
spec:
  interval: 5m
  chart:
    spec:
      chart: arc
      version: "0.8.1"
      sourceRef:
        kind: HelmRepository
        name: arc
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 3
    metrics:
      controllerManagerAddr: ":8080"
      listenerAddr: ":8080"
      listenerEndpoint: "/metrics"
