apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: eraser
  namespace: eraser-system
spec:
  interval: 5m
  chart:
    spec:
      chart: eraser
      version: '1.3.0'
      sourceRef:
        kind: HelmRepository
        name: eraser
        namespace: flux-system
      interval: 1m
  values:
    runtimeConfig:
      components:
        scanner:
          enabled: false