apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nfs-subdir
  namespace: nfs-subdir-system
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: '4.0.18'
      sourceRef:
        kind: HelmRepository
        name: nfs
        namespace: flux-system
      interval: 1m
  values:
    storageClass:
      name: nfs-client
    nfs:
      server: synology.gravitytech.io
      path: /volume1/k8s_nfs
