apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: config-github-webhook
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-kv-store
  target:
    name: argocd-secret
    creationPolicy: Merge
    deletionPolicy: Merge
    template:
      type: Opaque
      engineVersion: v2
      data:
        webhook.github.secret: "{{ .key }}"
  data:
    - secretKey: key
      remoteRef:
        key: secret/argo-github-webhook-secret