apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-kv-store
  target:
    template:
      engineVersion: v2
      data:
        api-token: '{{.token}}'
  data:
    - secretKey: token
      remoteRef:
        key: secret/cloudflare-api-token-gravitytech-io