apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-kv-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      serviceAccountRef:
        name: cert-manager-wi
      vaultUrl: https://k3s-wi-test.vault.azure.net/
