apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-volume
  namespace: harbor
spec:
  storageClassName: nfs-harbor
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: synology.gravitytech.io
    path: /volume1/harbor