apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-claim
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: harbor-volume