apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: smb-csi
  namespace: smb-csi-system
spec:
  interval: 5m
  chart:
    spec:
      chart: csi-driver-smb
      version: "v1.9.0"
      sourceRef:
        kind: HelmRepository
        name: smb
        namespace: flux-system
      interval: 1m
  values:
