apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: azure-workload-identity-system
  namespace: azure-workload-identity-system
spec:
  interval: 5m
  chart:
    spec:
      chart: workload-identity-webhook
      version: '1.2.0'
      sourceRef:
        kind: HelmRepository
        name: azure-workload-identity
        namespace: flux-system
      interval: 1m
  values:
    azureTenantID: 8c366e63-876b-4edc-b2b4-f83942b3ee56