apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - "applications/azwi.yaml"
  - "applications/eraser.yaml"
  - "applications/external-secrets.yaml"
  - "applications/flux.yaml"
  - "applications/ingress.yaml"
  - "applications/kps.yaml"