apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - "applications/arc.yaml"
  - "applications/azwi.yaml"
  - "applications/cert-manager.yaml"
  - "applications/eraser.yaml"
  - "applications/external-secrets.yaml"
  - "applications/flux.yaml"
  - "applications/harbor.yaml"
  - "applications/ingress.yaml"
  - "applications/kps.yaml"
  - "applications/nfs.yaml"
  - "applications/smb.yaml"

  - "secrets/sa.yaml"
  - "secrets/store.yaml"
  - "secrets/webhook.yaml"