apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx-external
  namespace: ingress-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '4.9.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 1m
  values:
    controller:
      replicaCount: 3
      service:
        loadBalancerIP: 192.168.20.128
      ingressClassResource:
        name: external-nginx
        enabled: true
        default: false
        controllerValue: "k8s.io/external-ingress-nginx"