apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  # Install Flux
  - https://github.com/fluxcd/flux2/manifests/install?ref=v2.2.2

  # Add Helm Repositories
  - helm/atlassian.yaml
  - helm/azure-workload-identity.yaml
  - helm/cert-manager.yaml
  - helm/external-secrets.yaml
  - helm/harbor.yaml
  - helm/nfs.yaml
  - helm/nginx.yaml
  - helm/sealed-secrets.yaml
  - helm/traefik.yaml