apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: weave-gitops
      version: '4.0.36'
      sourceRef:
        kind: HelmRepository
        name: weave-works
        namespace: flux-system
      interval: 1m
  values:
    adminUser:
      create: false