apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-management
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: argo-management
spec:
  project: default
  source:
    repoURL: https://github.com/brabe/k3s-lab-gitops
    targetRevision: HEAD
    path: argo/management

  # Destination cluster and namespace to deploy the application
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
