apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - app-management.yaml
  - ingress/internal.yaml
  - ingress/external.yaml
    # ArgoCD Version v2.9.5
  - https://github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.9.5

components:
  # ArgoCD Extensions
  - https://github.com/argoproj-labs/argocd-extensions/manifests?ref=v0.2.1

patches:
  - path: patch/argocd-cm.yaml
  - path: patch/argocd-cmd-params-cm.yaml
  - path: patch/argocd-server-cr.yaml
